site_name: PYBOSSA Documentation
#theme: 'material'
theme: 'readthedocs'
markdown_extensions:
    - tocm
    - toc:
        permalink: True
    - admonition
    - smarty
    - wikilinks
    - codehilite:
        linenums: True
    # - urlize # requires: pip install git+https://github.com/r0wb0t/markdown-urlize.git
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
#    - pymdownx.emoji:
#        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
#    - pymdownx.tasklist:
#        custom_checkbox: True
    - pymdownx.tilde
    - pymdownx.progressbar
    - pymdownx.tabbed
    - pymdownx.extra
